spring:
  application:
    name: file-service
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 150Mb
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@peer1:8761/eureka/,http://admin:admin123@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true