spring:
  application:
    name: user-service
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost