spring:
  application:
    name: book-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@peer1:8761/eureka/,http://admin:admin123@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    sample.bookservice.integration.UserServiceClient: DEBUG

security:
  basic:
    enabled: true
    path: /manager
  user:
    name: admin
    password: admin123
management:
  security.enabled: true
  context-path: /manager

feign:
  hystrix:
   enabled: true
