security:
  basic:
    enabled: true
  user:
    name: conf
    password: conf123
management:
  security.enabled: true
  context-path: /manager

eureka:
  instance:
    healthCheckUrlPath: ${management.context-path}/health
    statusPageUrlPath: ${management.context-path}/info
    metadata-map:
      management.context-path: ${management.context-path}
      user:
        name: ${security.user.name}
        password: ${security.user.password}
  client.healthcheck.enabled: true
