spring:
  application:
    name: hystrix-service
server:
  port: 8030
eureka:
  client:
    serviceUrl:
     defaultZone: http://admin:admin123@peer1:8761/eureka/,http://admin:admin123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: book-service
  instanceUrlSuffix: /manager/hystrix.stream
  clusterNameExpression: new String('default')
