spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 150Mb
server:
  port: 8082

security:
  basic:
    enabled: true
    path: /manager
  user:
    name: admin
    password: admin123
management:
  security.enabled: true
  context-path: /manager

feign:
  hystrix:
   enabled: true

eureka:
  instance:
    healthCheckUrlPath: ${management.context-path}/health
    statusPageUrlPath: ${management.context-path}/info
    metadata-map.management.context-path: ${management.context-path}
  client.healthcheck.enabled: true